[build]
  baseDir = "packages/app"
  publish = "dist"
  command = "npm run deploy:app"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = ".netlify/functions"
  node_bundler = "none"
  included_files = [".netlify/functions/**"]
