[build]
  publish = "packages/app/dist"
  command = "npm run deploy:app"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "packages/app/.netlify/functions"
  node_bundler = "none"
  included_files = [".netlify/functions/**"]
